import { Family, Profile, Store, Product, PriceHistory, ShoppingList, ListItemEnriched } from './types/database';

export const DEMO_FAMILY: Family = {
  id: 'fam-demo-001',
  name: 'Familia González',
  invite_code: 'MAND-8A42',
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const DEMO_PROFILES: Profile[] = [];

export const DEMO_STORES: Store[] = [
  {
    id: 'store-dia',
    family_id: 'fam-demo-001',
    name: 'Supermercado Dia',
    category: 'supermercado',
    address: 'Adolfo Alsina 534, General Pinto',
    lat: -34.7648413,
    lng: -61.8927143,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: 'store-gauchito',
    family_id: 'fam-demo-001',
    name: 'Supermercado El Gauchito',
    category: 'supermercado',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7651100,
    lng: -61.8900772,
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: 'store-valeria',
    family_id: 'fam-demo-001',
    name: 'Pollería Valeria',
    category: 'carniceria',
    address: 'Adolfo Alsina 559, General Pinto',
    lat: -34.7649500,
    lng: -61.8929000,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'store-justy',
    family_id: 'fam-demo-001',
    name: 'Carnicería Justy',
    category: 'carniceria',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7645000,
    lng: -61.8918000,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'store-gao',
    family_id: 'fam-demo-001',
    name: 'Súper GAO',
    category: 'supermercado',
    address: 'Sarmiento 342, General Pinto',
    lat: -34.7652183,
    lng: -61.8935359,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'store-charitos',
    family_id: 'fam-demo-001',
    name: 'Carnicería Los Charitos',
    category: 'carniceria',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7658000,
    lng: -61.8942000,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
];

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-ddl',
    family_id: 'fam-demo-001',
    name: 'Dulce de Leche 400g',
    canonical_store_id: 'store-dia', // Dia is canonical ($1450 vs $1590 en Super GAO)
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prod-shampoo',
    family_id: 'fam-demo-001',
    name: 'Shampoo Nutritivo 400ml',
    canonical_store_id: 'store-dia', // Dia ($2900 vs $3200 en Super GAO)
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prod-asado',
    family_id: 'fam-demo-001',
    name: 'Tira de asado',
    canonical_store_id: 'store-justy', // Justy ($7800 vs $8200 en Los Charitos)
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prod-pollo',
    family_id: 'fam-demo-001',
    name: 'Suprema de pollo',
    canonical_store_id: 'store-valeria', // Pollería Valeria ($5400 vs $6100 en Dia)
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prod-manzana',
    family_id: 'fam-demo-001',
    name: 'Manzana roja',
    canonical_store_id: 'store-gauchito', // El Gauchito ($1800 vs $2400 en Dia)
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prod-banana',
    family_id: 'fam-demo-001',
    name: 'Banana',
    canonical_store_id: 'store-gauchito',
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
];

export const DEMO_PRICE_HISTORY: PriceHistory[] = [];

export const DEMO_LISTS: ShoppingList[] = [
  {
    id: 'list-family-001',
    family_id: 'fam-demo-001',
    owner_id: null,
    name: 'Lista: Familiar',
    is_shared: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'list-personal-001',
    family_id: 'fam-demo-001',
    owner_id: 'user-demo-001',
    name: 'Lista: Asado del Domingo',
    is_shared: false,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const DEMO_LIST_ITEMS: ListItemEnriched[] = [
  {
    id: 'item-1',
    list_id: 'list-family-001',
    product_id: 'prod-ddl',
    store_id: 'store-dia',
    is_store_override: false,
    quantity: 2,
    unit: 'unidad',
    checked: false,
    added_by: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    product: DEMO_PRODUCTS[0],
    store: DEMO_STORES[0],
    canonical_store: DEMO_STORES[0],
    latest_price: 1450,
    price_recorded_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    is_price_outdated: false,
    canonical_latest_price: 1450,
  },
  {
    id: 'item-2',
    list_id: 'list-family-001',
    product_id: 'prod-shampoo',
    store_id: 'store-dia',
    is_store_override: false,
    quantity: 1,
    unit: 'unidad',
    checked: false,
    added_by: null,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    product: DEMO_PRODUCTS[1],
    store: DEMO_STORES[0],
    canonical_store: DEMO_STORES[0],
    latest_price: 2900,
    price_recorded_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    is_price_outdated: false,
    canonical_latest_price: 2900,
  },
  {
    id: 'item-3',
    list_id: 'list-family-001',
    product_id: 'prod-asado',
    store_id: 'store-justy',
    is_store_override: false,
    quantity: 1.5,
    unit: 'kg',
    checked: false,
    added_by: 'user-demo-001',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    product: DEMO_PRODUCTS[2],
    store: DEMO_STORES[3],
    canonical_store: DEMO_STORES[3],
    latest_price: 7800,
    price_recorded_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    is_price_outdated: false,
    canonical_latest_price: 7800,
  },
  {
    id: 'item-4',
    list_id: 'list-family-001',
    product_id: 'prod-pollo',
    store_id: 'store-valeria',
    is_store_override: false,
    quantity: 1,
    unit: 'kg',
    checked: false,
    added_by: 'user-demo-002',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    product: DEMO_PRODUCTS[3],
    store: DEMO_STORES[2],
    canonical_store: DEMO_STORES[2],
    latest_price: 5400,
    price_recorded_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    is_price_outdated: false,
    canonical_latest_price: 5400,
  },
  {
    id: 'item-5',
    list_id: 'list-family-001',
    product_id: 'prod-manzana',
    store_id: 'store-gauchito',
    is_store_override: false,
    quantity: 1,
    unit: 'kg',
    checked: true,
    added_by: 'user-demo-002',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    product: DEMO_PRODUCTS[4],
    store: DEMO_STORES[1],
    canonical_store: DEMO_STORES[1],
    latest_price: 1800,
    price_recorded_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    is_price_outdated: false,
    canonical_latest_price: 1800,
  },
  {
    id: 'item-6',
    list_id: 'list-family-001',
    product_id: 'prod-banana',
    store_id: 'store-gauchito',
    is_store_override: false,
    quantity: 5,
    unit: 'unidad',
    checked: false,
    added_by: 'user-demo-003',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    product: DEMO_PRODUCTS[5],
    store: DEMO_STORES[1],
    canonical_store: DEMO_STORES[1],
    latest_price: 1500,
    price_recorded_at: new Date(Date.now() - 9 * 86400000).toISOString(), // Outdated!
    is_price_outdated: true,
    canonical_latest_price: 1500,
  },
];
