import { Family, Profile, Store, Product, PriceHistory, ShoppingList, ListItemEnriched } from './types/database';

export const DEFAULT_FAMILY: Family = {
  id: 'fam-default-001',
  name: 'Mi Familia',
  invite_code: 'MANDADO-7X9K2W',
  created_at: new Date().toISOString(),
};

export const DEFAULT_PROFILES: Profile[] = [];

export const DEFAULT_STORES: Store[] = [
  {
    id: 'store-dia',
    family_id: 'fam-default-001',
    name: 'Supermercado Dia',
    category: 'supermercado',
    address: 'Adolfo Alsina 534, General Pinto',
    lat: -34.7648413,
    lng: -61.8927143,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-gauchito',
    family_id: 'fam-default-001',
    name: 'Supermercado El Gauchito',
    category: 'supermercado',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7651100,
    lng: -61.8900772,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-valeria',
    family_id: 'fam-default-001',
    name: 'Pollería Valeria',
    category: 'carniceria',
    address: 'Adolfo Alsina 559, General Pinto',
    lat: -34.7649500,
    lng: -61.8929000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-justy',
    family_id: 'fam-default-001',
    name: 'Carnicería Justy',
    category: 'carniceria',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7645000,
    lng: -61.8918000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-gao',
    family_id: 'fam-default-001',
    name: 'Súper GAO',
    category: 'supermercado',
    address: 'Sarmiento 342, General Pinto',
    lat: -34.7652183,
    lng: -61.8935359,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-charitos',
    family_id: 'fam-default-001',
    name: 'Carnicería Los Charitos',
    category: 'carniceria',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7658000,
    lng: -61.8942000,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-sanfra',
    family_id: 'fam-default-001',
    name: 'Sanfra',
    category: 'supermercado',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7684858,
    lng: -61.8879621,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-berlin',
    family_id: 'fam-default-001',
    name: 'Supermercado Berlín',
    category: 'supermercado',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7692101,
    lng: -61.8913783,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-la-chacra',
    family_id: 'fam-default-001',
    name: 'Carnicería La Chacra',
    category: 'carniceria',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7681164,
    lng: -61.8890326,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-pollería-amigos',
    family_id: 'fam-default-001',
    name: 'Pollería Los Amigos',
    category: 'carniceria',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7671451,
    lng: -61.8899217,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-kiosco84',
    family_id: 'fam-default-001',
    name: 'Kiosco 84',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7630799,
    lng: -61.8904834,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-free-pazz',
    family_id: 'fam-default-001',
    name: 'Kiosco Free PAZZ',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7660178,
    lng: -61.8913423,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-rey-sol',
    family_id: 'fam-default-001',
    name: 'Kiosco Rey Sol',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7678752,
    lng: -61.8913943,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-buena-vida',
    family_id: 'fam-default-001',
    name: 'Dietética Buena Vida',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7683016,
    lng: -61.8881593,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-luna',
    family_id: 'fam-default-001',
    name: 'Supermercado Luna',
    category: 'supermercado',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7635117,
    lng: -61.8894490,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-la-garita',
    family_id: 'fam-default-001',
    name: 'Autoservicio La Garita',
    category: 'supermercado',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7700637,
    lng: -61.8869584,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-los-abuelos',
    family_id: 'fam-default-001',
    name: 'Panadería Los Abuelos',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7635545,
    lng: -61.8907016,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-las-bambinas',
    family_id: 'fam-default-001',
    name: 'Panadería Las Bambinas',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7652718,
    lng: -61.8910530,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-la-italiana',
    family_id: 'fam-default-001',
    name: 'Panadería La Italiana',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7657701,
    lng: -61.8909698,
    created_at: new Date().toISOString(),
  },
  {
    id: 'store-2-abril',
    family_id: 'fam-default-001',
    name: 'Panadería 2 de Abril',
    category: 'otro',
    address: 'General Pinto, Buenos Aires',
    lat: -34.7645533,
    lng: -61.8924035,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_PRODUCTS: Product[] = [];

export const DEFAULT_PRICE_HISTORY: PriceHistory[] = [];

export const DEFAULT_LISTS: ShoppingList[] = [
  {
    id: 'list-family-001',
    family_id: 'fam-default-001',
    owner_id: null,
    name: 'Lista: Familiar',
    is_shared: true,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_LIST_ITEMS: ListItemEnriched[] = [];
